version: 0.0
os: linux	
files:	
  - source: /	  
    destination: /var/deploy/tmp/	    
hooks:	
  BeforeInstall:
    - location: scripts/install_dep   
      timeout: 300	     
      runas: root
    - location: scripts/release  
      timeout: 300	     
      runas: root	     
    - location: scripts/start_server	    
      timeout: 300	     
      runas: root
