#!/bin/bash
copytime=$(date +%Y%m%d%H%M%S)
sudo mkdir /var/deploy/release/$copytime
sudo mv /var/deploy/tmp/* /var/deploy/release/$copytime/
sudo rm -rf /var/deploy/current
sudo ln -s /var/deploy/release/$copytime /var/deploy/current
