#!/bin/bash
copytime=$(date +%Y%m%d%H%M%S)
sudo mkdir /var/deploy/release/$copytime
sudo sed -i 's/font>/font>\n<p> $copytime <\/p>/g' /var/deploy/tmp/index.html
sudo mv /var/deploy/tmp/* /var/deploy/release/$copytime/
sudo rm -rf /var/deploy/current
sudo ln -s /var/deploy/release/$copytime /var/deploy/current
